#! /bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi

set -e

# On Linux, NumPy fails to compile unless we link with the "-shared" option. On
# Mac, NumPy compiles out of the box.
if [ "$(uname)" = "Linux" ]; then
    export LDFLAGS="${LDFLAGS} -shared"
fi

echo "[DEFAULT]" > site.cfg
echo "library_dirs = $SPKG_LOCAL/lib" >> site.cfg
echo "include_dirs = $SPKG_LOCAL/include" >> site.cfg
echo "" >> site.cfg

rm -rf "$SPKG_LOCAL"/lib/python/site-packages/numpy
python setup.py install
